### ISSUE TITLE
Delete,Update,GetByName api's are not working

### ISSUE THREAD

**Issue by arcis123umair** [nikhilsbhat/gocd-sdk-go#2]
Hi Sir,
I was using this sdk to implement CRUD for K8S Elastic Agent and Cluster Profile. At the time of testing for my CRUD, only Create and GetAll Api's are working, while calling GetByName,Delete or Update i was getting code 400 Error.

Error:- 
got 400 from GoCD while making DELETE call for http://server-ip:port/go/%5Capi%5Cadmin%5Celastic%5Ccluster_profiles%5Ccluster4
with BODY:

**Comment by nikhilsbhat** [comment]
Can you elaborate the problem with some example?

Getting a specific cluster profile is supported and it is working for me. Check this out in the [example](https://github.com/nikhilsbhat/gocd-sdk-go/blob/master/examples/cluster_profiles.go#L63)

Have used the same in the terraform provider too, for [ref](https://github.com/nikhilsbhat/terraform-provider-gocd/blob/main/internal/provider/resource_cluster_profile.go#L136).

**Comment by arcis123umair** [comment]
Here is my code to getClusterProfile(name)
```func (u UserImpl) GetClusterProfileById(id string) (gocd.CommonConfig, error) {
	fmt.Println("Profile:", id)
	get, err := client.GetClusterProfile(id)
	fmt.Println("Get Cluster", get)
	if err != nil {
		fmt.Println("This error occurs inside Dao GetClusterProfileById function", err)
	}
	return get, err
}```

```func GetClusterProfileByName(w http.ResponseWriter, r *http.Request)  {
	w.Header().Set("Content-Type", "application/json")
	n := mux.Vars(r)
	getById, err  := dao2.GetClusterProfileById(n["id"])
	fmt.Println("Get By ID:", getById)
	if err != nil {
		fmt.Println("This error occurs while getting Cluster Profile By Name", err)
	}
	json.NewEncoder(w).Encode(getById)
}```

Following Error output-

Profile: cluster4
{"level":"warning","msg":"Using Basic Auth in HTTP mode is not secure, use HTTPS","time":"2023-04-07T11:46:51+05:30"}
Get Cluster {     false [] [] }
This error occurs inside Dao GetClusterProfileById function got 400 from GoCD while making GET call for http://10.100.100.65:32541/go/%5Capi%5Cadmin%5Celastic%5Ccluster_profiles%5Ccluster4
with BODY:
Get By ID: {     false [] [] }
This error occurs while getting Cluster Profile By Name got 400 from GoCD while making GET call for http://10.100.100.65:32541/go/%5Capi%5Cadmin%5Celastic%5Ccluster_profiles%5Ccluster4
with BODY:

Hope it is helpful

**Comment by nikhilsbhat** [comment]
Hey @arcis123umair, 

May I know the GoCD version and also the library version that is being used?
I will try to reproduce the issue in my local.

**Comment by arcis123umair** [comment]
Hello @nikhilsbhat 

GoCD version: v22.3.0
Library version: v0.1.1
